1. Go 语言的函数属于“一等公民”（first-class），也就是说：
   **函数本身可以作为值进行传递。**
   **支持匿名函数和闭包（closure）。**
   **函数可以满足接口。**

2. 函数也是一种类型，所以：定义了相同类型和数量的参数、相同类型和数量的返回值的函数变量可以被赋值其它函数或方法。

3. Go语言中传入与返回参数在调用和返回时都使用值传递，这里需要注意的是指针、切片和 map 等引用型对象在参数传递中不会发生复制，而是将指针进行复制，类似于创建一次引用。

4. Go 语言的匿名函数可以赋值给一个变量或者直接执行：

   ```go
   add := func(a, b int) int {
       return a + b
   }
   
   fmt.Println(add(1, 2))  // 调用匿名函数 add
   
   func(a, b int) {
       fmt.Println(a + b)
   } (1, 2) // 花括号后直接跟参数列表表示直接调用函数
   ```

   Go 支持闭包：

   Go 语言中的闭包同样也会引用函数外定义的变量，只要闭包还在被使用，那么被闭包引用的变量会一直存在。

   ```go
   import "fmt"
   
   func main() {
       i := 10
       add := func (a, b int) {
           fmt.Printf("Variable i from main func: %d\n", i)
           fmt.Printf("The sum of %d and %d is: %d\n", a, b, a+b)
       }
       callback(1, add);
   }
   
   func callback(x int, f func(int, int)) {
       f(x, 2)
   }
   ```

   作为返回值：

   ```go
   package main
   
   import "fmt"
   
   func main() {
       f := addfunc(1)
       fmt.Println(f(2))
   }
   
   func addfunc(a int) func(b int) int {
       return func(b int) int {
           return a + b
       }
   }
   ```

5. 函数和其他类型一样都属于“一等公民”，其他类型能够实现接口，函数也可以。

6. 当 panic() 触发的宕机发生时，panic() 后面的代码将不会被运行，但是在 panic() 函数前面已经运行过的 defer 语句依然会在宕机发生时发生作用。

7. panic 和 recover 的关系

   panic 和 recover 的组合有如下特性：

   - 有 panic 没 recover，程序宕机。
   - 有 panic 也有 recover，程序不会宕机，执行完对应的 defer 后，从宕机点退出当前函数后继续执行。

   提示

   虽然 panic/recover 能模拟其他语言的异常机制，但并不建议在编写普通函数时也经常性使用这种特性。

   在 panic 触发的 defer 函数内，可以继续调用 panic，进一步将错误外抛，直到程序整体崩溃。

   如果想在捕获错误时设置当前函数的返回值，可以对返回值使用命名返回值方式直接进行设置。

8. Go语言的 testing 包提供了三种测试方式，分别是**单元**（功能）测试、**性能**（压力）测试和**覆盖率**测试。

